### PR TITLE
Add the action

### PR DESCRIPTION
**Pull request by kumekay**
Move the action from https://github.com/espressif/github-actions/tree/master/upload_components to the separate repo

### CODE REVIEW

**Comment by kumekay** [comment]
@magicarm22 PTAL

**Comment by magicarm22** [comment]
@kumekay LGTM, thanks!

**Comment by igrr** [comment]
@kumekay would you consider preserving the commit history (like it is done in the esp-protocols repository, for example)?

**Comment by tomassebestik** [comment]
Hi @kumekay,
LGTM, it's great that we can now use version tags. Thank you.
___
Please check and review the related [GitLab MR](https://gitlab.espressif.cn:6688/espressif/repository-templates/github-actions-component-manager/-/merge_requests/1).

This is the GH action boilerplate used by the internal `Create Project Tools`  - changed the path (repository) from which this action is called (one line change). I have marked you there.

**Review by tomassebestik — APPROVED** [review]
Hi @kumekay,
LGTM, it's great that we can now use version tags. Thank you.
___
Please check and review the related [GitLab MR](https://gitlab.espressif.cn:6688/espressif/repository-templates/github-actions-component-manager/-/merge_requests/1).

This is the GH action boilerplate used by the internal `Create Project Tools`  - changed the path (repository) from which this action is called (one line change). I have marked you there.

**Comment by kumekay** [comment]
> @kumekay would you consider preserving the commit history (like it is done in the esp-protocols repository, for example)?

Excellent idea. I'll keep some history

**Pull request closed without merging**
