### PR TITLE
Update component manager and base python docker image

### PR DESCRIPTION
**Pull request by kumekay**
Use component manager 2.0 and python 3.12 in the job

### CODE REVIEW

**Comment by kumekay** [comment]
A successful job with this change: https://github.com/espressif/example_components/actions/runs/10453323777/job/28943553750

**Comment by kumekay** [comment]
@hfudev @tomassebestik PTAL

**Review by tomassebestik — APPROVED** [review]
LGTM!

**Comment by kumekay** [comment]
@tomassebestik  Thank you for taking a look!

**Review by hfudev — APPROVED** [review]

**Pull request merged**
